"use client";

import { useState } from "react";
import { useApi } from "@/components/ApiContext";
import { Badge, Field, FieldError, FormActions, LoadState, Modal, PageHeader, useData, useSubmit } from "@/components/ui";
import { Application, Paged, Server } from "@/types/api";

type FormModel = Application & { serverIds: string[] };
const blank: FormModel = { id: "", name: "", environment: "Prod", description: "", criticality: "Medium", applicationType: "COTS", currentVersion: "", migrationScope: "In Scope", migrationStrategy: "Investigate", migrationStatus: "Not Started", associatedServers: [], serverIds: [] };

export default function ApplicationsPage() {
  const { api } = useApi(); const [search, setSearch] = useState("");
  const { data, loading, error, reload } = useData<Paged<Application>>(`/api/applications?pageSize=200&search=${encodeURIComponent(search)}`);
  const { data: servers } = useData<Paged<Server>>("/api/servers?pageSize=200");
  const [editing, setEditing] = useState<FormModel | null>(null); const { saving, formError, submit } = useSubmit(() => { setEditing(null); void reload(); });
  const open = (app?: Application) => setEditing(app ? { ...app, serverIds: app.associatedServers.map(x => x.id) } : blank);
  const save = (item: FormModel) => api(item.id ? `/api/applications/${item.id}` : "/api/applications", { method: item.id ? "PUT" : "POST", body: JSON.stringify(item) });
  return <><PageHeader eyebrow="Inventory" title="Applications" description="Application scope, criticality, strategy and server relationships." action={<button className="button primary" onClick={() => open()}>New application</button>} />
    <div className="toolbar"><label className="search"><span>⌕</span><input placeholder="Search applications" value={search} onChange={e => setSearch(e.target.value)} /></label><span>{data?.totalCount ?? 0} applications</span></div>
    <LoadState loading={loading} error={error}><div className="table-wrap"><table><thead><tr><th>Application</th><th>Environment</th><th>Criticality</th><th>Type / Version</th><th>Scope</th><th>Strategy</th><th>Status</th><th>Associated servers</th><th /></tr></thead><tbody>{data?.items.map(app => <tr key={app.id}><td><strong>{app.name}</strong><small>{app.description}</small></td><td><Badge value={app.environment} /></td><td><Badge value={app.criticality} /></td><td>{app.applicationType}<small>{app.currentVersion || "—"}</small></td><td>{app.migrationScope}</td><td><strong>{app.migrationStrategy}</strong></td><td><Badge value={app.migrationStatus} /></td><td><div className="chips">{app.associatedServers.map(x => <span key={x.id}>{x.name}</span>)}</div></td><td><button className="text-button" onClick={() => open(app)}>Edit</button></td></tr>)}</tbody></table></div></LoadState>
    {editing && <Modal title={editing.id ? "Edit application" : "Create application"} onClose={() => setEditing(null)}><form onSubmit={e => submit(e, () => save(editing))}><div className="form-grid"><Field label="Application name" wide><input required value={editing.name} onChange={e => setEditing({ ...editing, name: e.target.value })} /></Field><Field label="Description" wide><textarea value={editing.description} onChange={e => setEditing({ ...editing, description: e.target.value })} /></Field><Field label="Environment"><select value={editing.environment} onChange={e => setEditing({ ...editing, environment: e.target.value })}>{["Prod","UAT","Dev","Test"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Criticality"><select value={editing.criticality} onChange={e => setEditing({ ...editing, criticality: e.target.value })}>{["Critical","High","Medium","Low"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Application type"><input required value={editing.applicationType} onChange={e => setEditing({ ...editing, applicationType: e.target.value })} /></Field><Field label="Current version"><input value={editing.currentVersion} onChange={e => setEditing({ ...editing, currentVersion: e.target.value })} /></Field><Field label="Migration scope"><select value={editing.migrationScope} onChange={e => setEditing({ ...editing, migrationScope: e.target.value })}>{["In Scope","Out of Scope","Under Review"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Migration strategy"><select value={editing.migrationStrategy} onChange={e => setEditing({ ...editing, migrationStrategy: e.target.value })}>{["Rehost","Build Ahead","Replatform","Refactor","SaaS","Retain","Retire","Investigate"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Migration status"><select value={editing.migrationStatus} onChange={e => setEditing({ ...editing, migrationStatus: e.target.value })}>{["Not Started","In Progress","Completed","Rolled Back","Blocked"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Associated servers" wide><select multiple value={editing.serverIds} onChange={e => setEditing({ ...editing, serverIds: Array.from(e.target.selectedOptions, x => x.value) })}>{servers?.items.map(x => <option value={x.id} key={x.id}>{x.hostname}</option>)}</select><small>Hold Ctrl to select multiple servers.</small></Field></div><FieldError value={formError} /><FormActions saving={saving} onCancel={() => setEditing(null)} /></form></Modal>}
  </>;
}
