"use client";

import { useState } from "react";
import { useApi } from "@/components/ApiContext";
import { Badge, Field, FieldError, FormActions, LoadState, Modal, PageHeader, formatDate, useData, useSubmit } from "@/components/ui";
import { Application, Decision, Paged } from "@/types/api";

const blank = { applicationId: "", migrationScope: "In Scope", migrationStrategy: "Investigate", targetPlatform: "Azure Virtual Machines", reason: "", risk: "Medium", decisionStatus: "Draft", decisionDate: "" };

export default function DecisionsPage() {
  const { api } = useApi(); const { data, loading, error, reload } = useData<Decision[]>("/api/migration-decisions"); const { data: apps } = useData<Paged<Application>>("/api/applications?pageSize=200");
  const [form, setForm] = useState(blank); const [open, setOpen] = useState(false); const { saving, formError, submit } = useSubmit(() => { setOpen(false); setForm(blank); void reload(); });
  return <><PageHeader eyebrow="Assessment" title="Migration Decisions" description="Approved scope, strategy, target platform and rationale for each workload." action={<button className="button primary" onClick={() => setOpen(true)}>Record decision</button>} />
    <LoadState loading={loading} error={error}><div className="table-wrap"><table><thead><tr><th>Application</th><th>Scope</th><th>Strategy</th><th>Target platform</th><th>Reason</th><th>Risk</th><th>Decision</th><th>Date</th></tr></thead><tbody>{data?.map(x => <tr key={x.id}><td><strong>{x.applicationName}</strong></td><td>{x.migrationScope}</td><td><Badge value={x.migrationStrategy} /></td><td>{x.targetPlatform}</td><td className="wide-cell">{x.reason}</td><td><Badge value={x.risk} /></td><td><Badge value={x.decisionStatus} /></td><td>{formatDate(x.decisionDate)}</td></tr>)}</tbody></table></div></LoadState>
    {open && <Modal title="Record migration decision" onClose={() => setOpen(false)}><form onSubmit={e => submit(e, () => api("/api/migration-decisions", { method: "POST", body: JSON.stringify(form) }))}><div className="form-grid"><Field label="Application" wide><select required value={form.applicationId} onChange={e => setForm({ ...form, applicationId: e.target.value })}><option value="">Select an application</option>{apps?.items.map(x => <option value={x.id} key={x.id}>{x.name}</option>)}</select></Field><Field label="Migration scope"><select value={form.migrationScope} onChange={e => setForm({ ...form, migrationScope: e.target.value })}>{["In Scope","Out of Scope","Under Review"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Strategy"><select value={form.migrationStrategy} onChange={e => setForm({ ...form, migrationStrategy: e.target.value })}>{["Rehost","Build Ahead","Replatform","Refactor","SaaS","Retain","Retire","Investigate"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Target platform" wide><input required value={form.targetPlatform} onChange={e => setForm({ ...form, targetPlatform: e.target.value })} /></Field><Field label="Reason" wide><textarea required value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })} /></Field><Field label="Risk"><select value={form.risk} onChange={e => setForm({ ...form, risk: e.target.value })}>{["Low","Medium","High","Critical"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Decision status"><select value={form.decisionStatus} onChange={e => setForm({ ...form, decisionStatus: e.target.value })}>{["Draft","Proposed","Approved","Rejected"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Decision date"><input type="date" value={form.decisionDate} onChange={e => setForm({ ...form, decisionDate: e.target.value })} /></Field></div><FieldError value={formError} /><FormActions saving={saving} onCancel={() => setOpen(false)} /></form></Modal>}
  </>;
}
