"use client";

import { useState } from "react";
import { useApi } from "@/components/ApiContext";
import { Badge, Empty, Field, FieldError, FormActions, LoadState, Modal, PageHeader, formatDate, useData, useSubmit } from "@/components/ui";
import { Application, DiscoverySnapshot, Paged, Server } from "@/types/api";

type FormModel = Server & { applicationIds: string[] };
const blank: FormModel = { id: "", hostname: "", environment: "Prod", operatingSystem: "Windows Server 2022", ipAddress: "", vCores: 4, memoryMb: 16384, allocatedStorageGb: 250, powerStatus: "On", migrationScope: "", migrationStrategy: "", migrationStatus: "Not Started", discoveryFreshness: "Unknown", associatedApplications: [], applicationIds: [] };
const sourceName = (value?: string) => value === "AzureMigrateAllInventoryReport" ? "Azure Migrate All Inventory" : value ? "Azure Migrate" : "—";

export default function ServersPage() {
  const { api } = useApi(); const [search, setSearch] = useState(""); const [environment, setEnvironment] = useState("");
  const { data, loading, error, reload } = useData<Paged<Server>>(`/api/servers?pageSize=200&search=${encodeURIComponent(search)}&environment=${environment}`);
  const { data: apps } = useData<Paged<Application>>("/api/applications?pageSize=200");
  const [editing, setEditing] = useState<FormModel | null>(null); const { saving, formError, submit } = useSubmit(() => { setEditing(null); void reload(); });
  const [historyServer, setHistoryServer] = useState<Server | null>(null); const [history, setHistory] = useState<DiscoverySnapshot[]>([]); const [historyError, setHistoryError] = useState("");
  const open = (server?: Server) => setEditing(server ? { ...server, applicationIds: server.associatedApplications.map(x => x.id) } : blank);
  const save = (item: FormModel) => api(item.id ? `/api/servers/${item.id}` : "/api/servers", { method: item.id ? "PUT" : "POST", body: JSON.stringify(item) });
  const openHistory = async (server: Server) => {
    setHistoryServer(server); setHistory([]); setHistoryError("");
    try { setHistory(await api<DiscoverySnapshot[]>(`/api/servers/${server.id}/discovery-history`)); }
    catch (exception) { setHistoryError(exception instanceof Error ? exception.message : "Unable to load discovery history."); }
  };

  return <><PageHeader eyebrow="Inventory" title="Servers" description="Infrastructure inventory linked to applications, discovery history and Azure target builds." action={<button className="button primary" onClick={() => open()}>New server</button>} />
    <div className="toolbar"><label className="search"><span>⌕</span><input placeholder="Hostname or IP address" value={search} onChange={e => setSearch(e.target.value)} /></label><select value={environment} onChange={e => setEnvironment(e.target.value)}><option value="">All environments</option>{["Prod","UAT","Dev","Test"].map(x => <option key={x}>{x}</option>)}</select><span>{data?.totalCount ?? 0} servers</span></div>
    <LoadState loading={loading} error={error}><div className="table-wrap"><table><thead><tr><th>Hostname</th><th>Environment</th><th>Applications</th><th>Current IP</th><th>Operating system</th><th>Compute</th><th>Power</th><th>Migration</th><th>Discovery source</th><th>Last discovered</th><th>Last imported</th><th>Support status</th><th>Azure target</th><th /></tr></thead><tbody>{data?.items.map(server => <tr key={server.id}><td><strong>{server.hostname}</strong></td><td><Badge value={server.environment} /></td><td><div className="chips">{server.associatedApplications.map(x => <span key={x.id}>{x.name}</span>)}</div></td><td className="mono">{server.ipAddress}</td><td>{server.operatingSystem}</td><td>{server.vCores ?? "—"} vCPU<small>{server.memoryMb ? `${server.memoryMb / 1024} GB RAM · ${server.allocatedStorageGb} GB` : "—"}</small></td><td><Badge value={server.powerStatus} /></td><td><Badge value={server.migrationStatus} /></td><td>{sourceName(server.discoverySource)}</td><td>{formatDate(server.lastDiscoveredAt)}<small><Badge value={server.discoveryFreshness} /></small></td><td>{formatDate(server.lastImportedAt)}</td><td>{server.supportStatus || "—"}</td><td>{server.azureTarget ? <span className="link-value">{server.azureTarget.name}</span> : "—"}</td><td><div className="table-actions"><button className="text-button" onClick={() => open(server)}>Edit</button><button className="text-button" onClick={() => void openHistory(server)}>Discovery history</button></div></td></tr>)}</tbody></table></div></LoadState>
    {editing && <Modal title={editing.id ? "Edit server" : "Create server"} onClose={() => setEditing(null)}><form onSubmit={e => submit(e, () => save(editing))}><div className="form-grid"><Field label="Hostname"><input required value={editing.hostname} onChange={e => setEditing({ ...editing, hostname: e.target.value })} /></Field><Field label="Environment"><select value={editing.environment} onChange={e => setEditing({ ...editing, environment: e.target.value })}>{["Prod","UAT","Dev","Test"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Operating system" wide><input required value={editing.operatingSystem} onChange={e => setEditing({ ...editing, operatingSystem: e.target.value })} /></Field><Field label="Current IP"><input value={editing.ipAddress} onChange={e => setEditing({ ...editing, ipAddress: e.target.value })} /></Field><Field label="vCPU"><input type="number" min="1" value={editing.vCores ?? ""} onChange={e => setEditing({ ...editing, vCores: Number(e.target.value) })} /></Field><Field label="Memory (MB)"><input type="number" min="1" value={editing.memoryMb ?? ""} onChange={e => setEditing({ ...editing, memoryMb: Number(e.target.value) })} /></Field><Field label="Storage (GB)"><input type="number" min="1" value={editing.allocatedStorageGb ?? ""} onChange={e => setEditing({ ...editing, allocatedStorageGb: Number(e.target.value) })} /></Field><Field label="Power status"><select value={editing.powerStatus} onChange={e => setEditing({ ...editing, powerStatus: e.target.value })}><option>On</option><option>Off</option><option>Unknown</option></select></Field><Field label="Migration status"><select value={editing.migrationStatus} onChange={e => setEditing({ ...editing, migrationStatus: e.target.value })}>{["Not Started","In Progress","Completed","Rolled Back","Blocked"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Associated applications" wide><select multiple value={editing.applicationIds} onChange={e => setEditing({ ...editing, applicationIds: Array.from(e.target.selectedOptions, x => x.value) })}>{apps?.items.map(x => <option value={x.id} key={x.id}>{x.name}</option>)}</select><small>Hold Ctrl to select multiple applications.</small></Field></div><FieldError value={formError} /><FormActions saving={saving} onCancel={() => setEditing(null)} /></form></Modal>}
    {historyServer && <Modal title={`Discovery history · ${historyServer.hostname}`} onClose={() => setHistoryServer(null)}><FieldError value={historyError} />{history.length ? <div className="snapshot-list">{history.map(snapshot => <article key={snapshot.id}><div><strong>{formatDate(snapshot.importedAt)}</strong><Badge value={snapshot.sourceType === "AzureMigrateAllInventoryReport" ? "All Inventory" : "Azure Migrate"} /></div><p><strong>{snapshot.vCores ?? "—"} vCPU</strong><strong>{snapshot.memoryMb ? `${snapshot.memoryMb / 1024} GB RAM` : "—"}</strong><span>{snapshot.operatingSystem || "Operating system unknown"}</span></p><small>{snapshot.ipAddresses || "No valid discovered IP"} · {snapshot.supportStatus || "Support unknown"}</small></article>)}</div> : !historyError && <Empty message="No discovery snapshots have been committed for this server." />}</Modal>}
  </>;
}
